# -*- coding: utf-8 -*-
"""Contador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fs3LERV9ehqrtFVtWulW2PH6Uzwk-gB
"""

codigo_contador = """
# Función que dice si un número es par o impar
def es_par_o_impar(n):
    if n % 2 == 0:         # Si el resto de dividir n por 2 es 0, es par
        return "par"
    else:
        return "impar"

# Función recursiva que cuenta desde n hasta 0
def cuenta_regresiva(n):
    if n < 0:
        return             # Caso base: si n es negativo, no hace nada
    print(f"{n} - {es_par_o_impar(n)}")  # Imprime el número y si es par o impar
    if n > 0:
        cuenta_regresiva(n - 1)           # Llama a sí misma con n-1 (recursión)
    else:
        print("🎉 ¡Llegaste a cero! 🎉")  # Mensaje especial al llegar a 0
"""

# Crear archivo contador.py
with open("contador.py", "w", encoding="utf-8") as f:
    f.write(codigo_contador)