# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMXiWyeqnhaBtRy4_H6qPN4SNwPYm1L0
"""

codigo_main = """
# Importamos el módulo contador.py con las funciones definidas
import contador

def main():
    try:
        # Pedimos al usuario un número entero positivo
        numero = int(input("Ingrese un número entero positivo: "))
        if numero < 0:
            print("El número debe ser positivo.")  # Mensaje si ingresan negativo
        else:
            print("\\nIniciando cuenta regresiva...\\n")
            # Llamamos a la función recursiva para iniciar la cuenta
            contador.cuenta_regresiva(numero)
    except ValueError:
        # Si el usuario no ingresa un número válido, muestra este mensaje
        print("Entrada inválida. Por favor ingrese un número entero.")

# Esta línea hace que main() se ejecute solo si corremos este archivo directamente
if __name__ == "__main__":
    main()
"""

# Crear archivo main.py
with open("main.py", "w", encoding="utf-8") as f:
    f.write(codigo_main)